var turn_info = [{
    "index": 1,
    "value": "红烧肉"
  }, {
    "index": 2,
    "value": "辣椒炒肉"
  }, {
    "index": 3,
    "value": "红烧茄子"
  }, {
    "index": 4,
    "value": "土豆丝"
  }, {
    "index": 5,
    "value": "煲仔饭"
  }, {
    "index": 6,
    "value": "酸辣鸡杂"
  }, {
    "index": 7,
    "value": "烤肉饭"
  }, {
    "index": 8,
    "value": "肯德基"
  }, {
    "index": 9,
    "value": "长沙米粉"
  }, {
    "index": 10,
    "value": "手撕包菜"
  }, {
    "index": 11,
    "value": "大葱炒肉"
  }, {
    "index": 12,
    "value": "洋葱炒肉"
  }, {
    "index": 13,
    "value": "回锅肉"
  }, {
    "index": 14,
    "value": "酸辣草鱼"
  }, {
    "index": 15,
    "value": "干锅红肠"
  }, {
    "index": 16,
    "value": "干锅牛蛙"
  }, {
    "index": 17,
    "value": "清蒸鱼"
  }, {
    "index": 18,
    "value": "麻婆豆腐"
  }, {
    "index": 19,
    "value": "番茄炒蛋"
  }, {
    "index": 20,
    "value": "酸辣粉"
  }, {
    "index": 21,
    "value": "广东烧腊"
  }, {
    "index": 22,
    "value": "黄焖鸡"
  }, {
    "index": 23,
    "value": "黄焖猪蹄"
  }, {
    "index": 24,
    "value": "青椒拆骨肉"
  }, {
    "index": 25,
    "value": "辣椒炒蛋"
  }, {
    "index": 26,
    "value": "酸爽梅干菜"
  }, {
    "index": 27,
    "value": "油麦菜"
  }, {
    "index": 28,
    "value": "剁椒芋头"
  }, {
    "index": 29,
    "value": "玉米排骨"
  }, {
    "index": 30,
    "value": "可乐鸡翅"
  }, {
    "index": 31,
    "value": "水蒸蛋"
  }, {
    "index": 32,
    "value": "红烧鱼块"
  }, {
    "index": 33,
    "value": "素羊肚丝"
  }, {
    "index": 34,
    "value": "清炒包菜"
  }, {
    "index": 35,
    "value": "扁豆炒肉"
  }, {
    "index": 36,
    "value": "萝卜烧鹅"
  }, {
    "index": 37,
    "value": "四季豆炒肉"
  }, {
    "index": 38,
    "value": "凉拌皮蛋"
  }, {
    "index": 39,
    "value": "雪里红肉末"
  }, {
    "index": 40,
    "value": "孜然牛肉"
  }, {
    "index": 41,
    "value": "藕片炒肉"
  }, {
    "index": 42,
    "value": "特色鸡排饭"
  }, {
    "index": 43,
    "value": "农家小炒肉"
  }, {
    "index": 44,
    "value": "煎饺肠粉"
  }, {
    "index": 45,
    "value": "大块腊肉"
  }, {
    "index": 46,
    "value": "麻辣香锅"
  }, {
    "index": 47,
    "value": "油豆腐炒肉"
  }, {
    "index": 48,
    "value": "香辣猪皮"
  }, {
    "index": 49,
    "value": "日料寿司"
  }, {
    "index": 50,
    "value": "这都能roll到，别吃了减肥"
  }
];

export {
  turn_info
}
